# Generated by Django 5.0.6 on 2024-07-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('videos', 'Video')
    ]
