# Generated by Django 5.0.6 on 2024-07-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(max_length=1000)),
                ('language', models.TextField(max_length=1000)),
                ('framework', models.TextField(max_length=1000)),
                ('description', models.TextField(max_length=3000)),
            ],
        ),
    ]
