# Generated by Django 5.0.6 on 2024-07-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_link',
            field=models.URLField(default='https://github.com/TactlessHermit?tab=repositories', max_length=2000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='framework',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='projects',
            name='language',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.TextField(max_length=250),
        ),
    ]
